apiVersion: v1
kind: Service
metadata:
  name: malaria-service
  labels:
    name: malaria-service
    app: malaria-app
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    name: malaria-app-pod
    app: malaria-app